package review.model;

public class Recommendations {
	protected int recommendationId;
	protected Users user;
	protected Restaurants restaurant;

	// This constructor can be used for reading records from MySQL, where we only
	// have the recommendationId, such as a foreign key reference to
	// RecommendationId.
	// Given RecommendationId, we can fetch the full RecommendationId record.
	public Recommendations(int recommendationId) {
		this.recommendationId = recommendationId;
	}

	// This constructor can be used for creating new records, where the
	// recommendationId may not be assigned yet since it is auto-generated by MySQL.
	public Recommendations(Users user, Restaurants restaurant) {
		this.user = user;
		this.restaurant = restaurant;
	}

	// This constructor can be used for reading records from MySQL, where we have
	// all fields, including the RecommendationId.
	public Recommendations(int recommendationId, Users user, Restaurants restaurant) {
		this.recommendationId = recommendationId;
		this.user = user;
		this.restaurant = restaurant;
	}

	public int getRecommendationId() {
		return recommendationId;
	}

	public void setRecommendationId(int recommendationId) {
		this.recommendationId = recommendationId;
	}

	public Users getUser() {
		return user;
	}

	public void setUser(Users user) {
		this.user = user;
	}

	public Restaurants getRestaurant() {
		return restaurant;
	}

	public void setRestaurant(Restaurants restaurant) {
		this.restaurant = restaurant;
	}

}
