package review.model;

import java.util.Date;

public class Reservations {
	protected int reservationId;
	protected Date start;
	protected Date end;
	protected int size;
	protected Users user;
	protected SitDownRestaurants sitDownRestaurants;

	// This constructor can be used for reading records from MySQL, where we only
	// have the reservationId, such as a foreign key reference to ReservationId.
	// Given ReservationId, we can fetch the full Reservations record.
	public Reservations(int reservationId) {
		this.reservationId = reservationId;
	}

	// This constructor can be used for creating new records, where the
	// reservationId may not be assigned yet since it is auto-generated by MySQL.
	public Reservations(Date start, Date end, int size, Users user, SitDownRestaurants sitDownRestaurants) {
		this.start = start;
		this.end = end;
		this.size = size;
		this.user = user;
		this.sitDownRestaurants = sitDownRestaurants;
	}

	// This constructor can be used for reading records from MySQL, where we have
	// all fields, including the ReservationId.
	public Reservations(int reservationId, Date start, Date end, int size, Users user,
			SitDownRestaurants sitDownRestaurants) {
		this.reservationId = reservationId;
		this.start = start;
		this.end = end;
		this.size = size;
		this.user = user;
		this.sitDownRestaurants = sitDownRestaurants;
	}

	public int getReservationId() {
		return reservationId;
	}

	public void setReservationId(int reservationId) {
		this.reservationId = reservationId;
	}

	public Date getStart() {
		return start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	public Date getEnd() {
		return end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	public int getSize() {
		return size;
	}

	public void setSize(int size) {
		this.size = size;
	}

	public Users getUser() {
		return user;
	}

	public void setUser(Users user) {
		this.user = user;
	}

	public SitDownRestaurants getSitDownRestaurants() {
		return sitDownRestaurants;
	}

	public void setSitDownRestaurants(SitDownRestaurants sitDownRestaurants) {
		this.sitDownRestaurants = sitDownRestaurants;
	}

}
